# Effects format: 'POTION_TYPE : DURATION : AMPLIFIER'

enabled: false
team-size: 1
min-teams: 2
lobby-countdown: 30
lobby-countdown-shortening:
  min-teams: 4
  shorten-to: 10
game-length: 2400
cage-lock-duration: 10
eggs-auto-destroy-time: 300
generators-upgrade: [1800, 1200, 600]
effects: ['NONE']