name: Eggwars
version: 7.2
author: Wazup92
main: me.wazup.eggwars.Eggwars
softdepend: [TitleManager, Vault, HolographicDisplays, PlaceholderAPI, MVdWPlaceholderAPI, FastAsyncWorldEdit, WorldEdit, Multiverse-Core, CrackShot, QualityArmory]
api-version: 1.13
commands:
  eggwars:
    description: Shows a list of commands related to Eggwars!
    aliases: [ew]